#!/usr/bin/env node
var cp = require('./utils/child-process-wrapper.js');
var fs = require('fs');
var path = require('path');

process.chdir(path.dirname(__dirname));

function loadEnvironmentVariables(filePath) {
  try {
    var lines = fs.readFileSync(filePath, 'utf8').trim().split('\n');
    for (i in lines) {
      var parts = lines[i].split('=');
      var key = parts[0].trim();
      var value = parts[1].trim().substr(1, parts[1].length - 2);
      process.env[key] = value;
    }
  } catch(error) {
    console.error("Failed to load environment variables: " + filePath, error.code);
  }
}

function readEnvironmentVariables() {
  loadEnvironmentVariables('/var/lib/jenkins/config/xcodekeychain');
}

readEnvironmentVariables();
cp.safeExec.bind(global, 'node script/bootstrap', function(error) {

  if (error)
    process.exit(1);

  var async = require('async');
  var gruntPath = path.join('node_modules', '.bin', 'grunt');

  var tasks = [
    //cp.safeExec.bind(global, 'git clean -dff'),
    cp.safeExec.bind(global, 'rm -Rf util'),
    cp.safeExec.bind(global, 'git clone git@github.com:VPNht/desktop-builder.git util'),
    cp.safeExec.bind(global, gruntPath + ' ci --stack --no-color')
  ]
  async.series(tasks, function(error) {
    process.exit(error ? 1 : 0);
  });
})();
